services:
  backend:
    build: .
    container_name: complete-backend
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: complete-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  frontend:
    build: ../frontend
    container_name: complete-frontend
    ports:
      - "80:80"
    restart: always

volumes:
  mongo-data:
